#!/usr/bin/env bash

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)"
export PATH="$PATH:${SCRIPT_DIR}"
export SITE=http://localhost:3000
export BACKEND=http://localhost:8080
export SWAGGER=http://localhost:8080/swagger-ui/index.html
